<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Stencil</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#variable</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#tag-filter</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#tag</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>begin</key>
			<string>\{#</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.begin.stencil</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>A comment.</string>
			<key>end</key>
			<string>#\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.end.stencil</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.block.stencil</string>
		</dict>
		<key>expression</key>
		<dict>
			<key>comment</key>
			<string>An expression that may include operators.</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>A keyword operator.</string>
					<key>match</key>
					<string>(?&lt;=\s)(?:and|or|not|in)(?=\s)</string>
					<key>name</key>
					<string>keyword.control.stencil</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>A symbolic operator.</string>
					<key>match</key>
					<string>(?&lt;=\s)(?:==|!=|&lt;|&gt;|&lt;=|&gt;=)(?=\s)</string>
					<key>name</key>
					<string>keyword.operator.stencil</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#filtered-value</string>
				</dict>
			</array>
		</dict>
		<key>filter</key>
		<dict>
			<key>applyEndPatternLast</key>
			<integer>1</integer>
			<key>begin</key>
			<string>\|</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.filter.begin.stencil</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>A filter.</string>
			<key>end</key>
			<string></string>
			<key>name</key>
			<string>meta.filter.stencil</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>The filter's name.</string>
					<key>match</key>
					<string>[^\s:|%}]+</string>
					<key>name</key>
					<string>support.function.filter.stencil</string>
				</dict>
				<dict>
					<key>applyEndPatternLast</key>
					<integer>1</integer>
					<key>begin</key>
					<string>:</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.filter-parameter.begin.stencil</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>The filter's parameters.</string>
					<key>end</key>
					<string></string>
					<key>name</key>
					<string>meta.filter-parameter.stencil</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#value</string>
						</dict>
						<dict>
							<key>comment</key>
							<string>A separator between filter parameters.</string>
							<key>match</key>
							<string>,</string>
							<key>name</key>
							<string>punctuation.separator.filter-parameter.stencil</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>filtered-value</key>
		<dict>
			<key>comment</key>
			<string>A value with zero or more filters applied.</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#value</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#filter</string>
				</dict>
			</array>
		</dict>
		<key>number</key>
		<dict>
			<key>comment</key>
			<string>A number literal.</string>
			<key>match</key>
			<string>(?&lt;=[\s\.:,{%])-?(?:0|[1-9]\d*)(?:\.\d+)?(?=[\s\.,|%}])</string>
			<key>name</key>
			<string>constant.numeric.stencil</string>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.stencil</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>A string literal.</string>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.stencil</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.stencil</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>An escape character.</string>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.stencil</string>
				</dict>
			</array>
		</dict>
		<key>tag</key>
		<dict>
			<key>begin</key>
			<string>(\{%)\s*([^\s%]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.stencil</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.stencil</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>A tag.</string>
			<key>end</key>
			<string>%\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.stencil</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.stencil</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>A keyword.</string>
					<key>match</key>
					<string>(?&lt;=\s)(?:in|where)(?=\s)</string>
					<key>name</key>
					<string>keyword.control.stencil</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>A separator between the key and value in a for tag.</string>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>punctuation.separator.key-value.stencil</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
			</array>
		</dict>
		<key>tag-filter</key>
		<dict>
			<key>begin</key>
			<string>(\{%)\s*(filter)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.stencil</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.stencil</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>A filter tag.</string>
			<key>end</key>
			<string>%\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.stencil</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.stencil</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>The initial filter's name.</string>
					<key>match</key>
					<string>[^\s:|%}]+</string>
					<key>name</key>
					<string>support.function.filter.stencil</string>
				</dict>
				<dict>
					<key>applyEndPatternLast</key>
					<integer>1</integer>
					<key>begin</key>
					<string>:</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.filter-parameter.begin.stencil</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>The initial filter's parameters.</string>
					<key>end</key>
					<string></string>
					<key>name</key>
					<string>meta.filter-parameter.stencil</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#value</string>
						</dict>
						<dict>
							<key>comment</key>
							<string>A separator between filter parameters.</string>
							<key>match</key>
							<string>,</string>
							<key>name</key>
							<string>punctuation.separator.filter-parameter.stencil</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#filter</string>
				</dict>
			</array>
		</dict>
		<key>value</key>
		<dict>
			<key>comment</key>
			<string>A property or literal.</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>A language-defined property.</string>
					<key>match</key>
					<string>\b(?&lt;!\.)(?:block|forloop)\b|(?&lt;=block\.)super\b|(?&lt;=forloop\.)(?:counter|counter0)\b|(?&lt;=\.)(?:first|last|count)\b</string>
					<key>name</key>
					<string>variable.language.stencil</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>A user-defined property.</string>
					<key>match</key>
					<string>[^\s\.,|%}]+</string>
					<key>name</key>
					<string>variable.other.stencil</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>A separator between properties.</string>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>punctuation.separator.property.stencil</string>
				</dict>
			</array>
		</dict>
		<key>variable</key>
		<dict>
			<key>begin</key>
			<string>\{\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.stencil</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>A variable.</string>
			<key>end</key>
			<string>\}\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.stencil</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.variable.stencil</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#filtered-value</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.stencil</string>
	<key>uuid</key>
	<string>52F8BC63-7858-4663-A322-2C1FFBBD324D</string>
</dict>
</plist>
