<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>stencil</string>
	</array>
	<key>name</key>
	<string>Stencil</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#variable</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#tag</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>begin</key>
			<string>\{#</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.begin.stencil</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>A comment.</string>
			<key>end</key>
			<string>#\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.end.stencil</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.block.stencil</string>
		</dict>
		<key>expression</key>
		<dict>
			<key>comment</key>
			<string>A Boolean expression.</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>A keyword operator.</string>
					<key>match</key>
					<string>(?&lt;=\s)(?:and|or|not)(?=\s)</string>
					<key>name</key>
					<string>keyword.control.stencil</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>A symbolic operator.</string>
					<key>match</key>
					<string>(?&lt;=\s)(?:==|!=|&lt;|&gt;|&lt;=|&gt;=)(?=\s)</string>
					<key>name</key>
					<string>keyword.operator.stencil</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#value</string>
				</dict>
			</array>
		</dict>
		<key>number</key>
		<dict>
			<key>comment</key>
			<string>A number constant.</string>
			<key>match</key>
			<string>(?&lt;=\s)-?(?:0|[1-9]\d*)(?:\.\d+)?(?=\s)</string>
			<key>name</key>
			<string>constant.numeric.stencil</string>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.stencil</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>A string constant.</string>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.stencil</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.stencil</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>A valid escape character.</string>
					<key>match</key>
					<string>\\[\\"tn]</string>
					<key>name</key>
					<string>constant.character.escape.stencil</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>An unsupported escape character.</string>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>invalid.illegal.character.escape.stencil</string>
				</dict>
			</array>
		</dict>
		<key>tag</key>
		<dict>
			<key>begin</key>
			<string>(\{%) ([a-zA-Z]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.stencil</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.stencil</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>A tag. Can be either a built-in tag or a custom one.</string>
			<key>end</key>
			<string>%\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.stencil</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.stencil</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>applyEndPatternLast</key>
					<integer>1</integer>
					<key>begin</key>
					<string>(?&lt;=\{%\sfilter)\s*</string>
					<key>comment</key>
					<string>A list of filters to apply in a filter tag.</string>
					<key>end</key>
					<string></string>
					<key>name</key>
					<string>meta.filter-list.stencil</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>comment</key>
							<string>A filter's name.</string>
							<key>match</key>
							<string>\b[a-zA-Z][a-zA-Z0-9]*\b</string>
							<key>name</key>
							<string>support.function.filter.stencil</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>:(?=")</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.filter-parameter.begin.stencil</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>A filter's parameter.</string>
							<key>end</key>
							<string>(?&lt;=")</string>
							<key>name</key>
							<string>meta.filter-parameter.stencil</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#string</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>comment</key>
							<string>A separator to chain filters.</string>
							<key>match</key>
							<string>\|</string>
							<key>name</key>
							<string>punctuation.definition.filter.begin.stencil</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>comment</key>
					<string>A keyword.</string>
					<key>match</key>
					<string>(?&lt;=\s)(?:in|where)(?=\s)</string>
					<key>name</key>
					<string>keyword.control.stencil</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>A separator between the key and value in a for tag.</string>
					<key>match</key>
					<string>,\s?</string>
					<key>name</key>
					<string>punctuation.separator.key-value.stencil</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
			</array>
		</dict>
		<key>value</key>
		<dict>
			<key>comment</key>
			<string>A constant or property. May include one or more filters.</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>A special property.</string>
					<key>match</key>
					<string>\b(?:block\.super|forloop\.(?:first|last|counter|counter0))\b</string>
					<key>name</key>
					<string>variable.language.stencil</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>A user-defined property. Can be several levels deep.</string>
					<key>match</key>
					<string>\b(?:[a-zA-Z][a-zA-Z0-9]*)(?:\.[a-zA-Z][a-zA-Z0-9]*)*\b</string>
					<key>name</key>
					<string>variable.other.stencil</string>
				</dict>
				<dict>
					<key>applyEndPatternLast</key>
					<integer>1</integer>
					<key>begin</key>
					<string>\|</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.filter.begin.stencil</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>A filter that can be applied to values. These can be chained.</string>
					<key>end</key>
					<string></string>
					<key>name</key>
					<string>meta.filter.stencil</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>comment</key>
							<string>The filter's name.</string>
							<key>match</key>
							<string>\b[a-zA-Z][a-zA-Z0-9]*\b</string>
							<key>name</key>
							<string>support.function.filter.stencil</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>:(?=")</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.filter-parameter.begin.stencil</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>The filter's parameter.</string>
							<key>end</key>
							<string>(?&lt;=")</string>
							<key>name</key>
							<string>meta.filter-parameter.stencil</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#string</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>variable</key>
		<dict>
			<key>begin</key>
			<string>\{\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.stencil</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>A variable. This evaluates a value.</string>
			<key>end</key>
			<string>\}\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.stencil</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.variable.stencil</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#value</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.stencil</string>
	<key>uuid</key>
	<string>52F8BC63-7858-4663-A322-2C1FFBBD324D</string>
</dict>
</plist>
